### ISSUE TITLE
Need config-sync Up/down metric

### ISSUE THREAD

**Issue by fowlerp-qlik** [solacecommunity/solace-prometheus-exporter#61]
There is no metric for event broker config-sync up/down. According to Solace the correct request is

```<rpc><show><config-sync></config-sync></show></rpc>```

and the response will be
```
<rpc-reply semp-version="soltr/10_5_1VMR">
  <rpc>
    <show>
      <config-sync>
        <status>
          <admin-status>Enabled</admin-status>
          <oper-status>Down</oper-status>
          <oper-status-down-reason>remote replication table has a problem: (2,Vpn,'someVpn') [Out-Of-Sync]</oper-status-down-reason>
          <ssl>true</ssl>
          .....
```
need to grab the value of  `<oper-status>`

**Comment by fowlerp-qlik** [comment]
I looked at both of those in the case where config-sync was down and both returned "good" results with no indication of a problem. I asked Solace about and they said that 

<rpc><show><config-sync></config-sync></show></rpc>

must be used. Sure enough that command returned a response that showed config-sync was down.

**Comment by GreenRover** [comment]
Please provide all Information solace provided or give me the solace ticket number.
At the moment i dont understand where the problem is.

**Comment by fowlerp-qlik** [comment]
Ticket is https://rt.solace.com/rt/Ticket/Display.html?id=98773. Let me know if you don't have access and I will make sure you get access.

**Comment by GreenRover** [comment]
I tried to take part to the ticket via email. You should see my message at rt.solace.com 
I am not able to this ticket via rt.solace.com (No permission to view ticket)
Lets see what solace respond.

**Comment by GreenRover** [comment]
I not jet received an response from solace. May be it not worked to post to your issue. I wrote to solace:

I try to understand why:
-	<show><config-sync><database/><router/></config-sync></show>
-	<show><config-sync><database/><message-vpn/><vpn-name>" + vpnFilter + "</vpn-name></config-sync></show>
Should provide oper-status In-Sync but:
- <show><config-sync></config-sync></show>

Would provide the “real”/Down oper-status.

Can you please make them answer?

**Comment by fowlerp-qlik** [comment]
I am back from Chistmas holidays. I see there was a Solace answer on Dec 26th. Does it answer your question. The config sync issue we had was resolved prior to Christmas so we cannot ge the the information Solace requested using the various cli commands.

**Comment by GreenRover** [comment]
Sorry i dint received the answer. Can you forward it?

**Comment by fowlerp-qlik** [comment]
Here is the answer 

> From: Russell Sim <>
> 
> Hi Heiko,
> 
> Note the question that you've raised is different from what was originally
> asked.
> 
> The previous question was why "<rpc><show><redundancy/></show></rpc>" shows UP
> while
> "/SEMP/v2/__private_monitor__/?select=configSyncUp,configSyncLastFailureReason"
> shows DOWN.
> The answer is that the first command is looking at redundancy and the other is
> looking at config-sync.
> They are not the same.
> 
> ---------
> 
> For your new question, we need more details on the exact error.
> For your particular issue on GitHub, the issue with config-sync is due to an
> issue with replication - "remote replication table has a problem:
> (2,Vpn,'someVpn')".
> 
> What does the output of the following CLI command return on both the DR active
> and DR standby sites?
> Please share the full output of the following.
> * show config-sync detail
> * show config-sync database detail
> * show config-sync database remote
> 
> Note that the "<show><config-sync><database/><router/></config-sync></show>"
> command does not matter to replication.
> This is used for configurations that are synced between HA but not
> replication.
> 
> Thanks,
> Russell
> 
> On Sat, 16 Dec 2023 01:33:05 +0800, heiko.henning wrote:
> 
>   Dear Solace,
> 
>   at first i am not from the same company as the ticket (#98773) owner.
>   There for I can not see the whole history of this ticket.
>   I got pointed to this ticket from Owner via:
>   [1]https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsolacecommunity%2Fsolace-prometheus-exporter%2Fissues%2F61&data=05%7C02%7Cpeter.fowler%40qlik.com%7C09a1ef8e3eba4fd35bc508dc06864a81%7Cc21eeb5ff5a644e8a997124f2f7a497c%7C0%7C0%7C638392421077963676%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=njaLo3xegPjoD4AcU6WY5VIye2fCeZmA6fLIKFysoDM%3D&reserved=0
> 
>   I try to understand why:
> 
> 
>     * <show><config-sync><database/><router/></config-sync></show>
>     * <show><config-sync><database/><message-vpn/><vpn-name>" + vpnFilter +
>       "</vpn-name></config-sync></show>
> 
> 
>   Should provide oper-status In-Sync but:
>   - <show><config-sync></config-sync></show>
> 
> 
> 
>   Would provide the "real"/Down oper-status.
> 
>   Please explain the difference.
> 
> 
> 
> References
> 
>    Visible links
>    1. https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsolacecommunity%2Fsolace-prometheus-exporter%2Fissues%2F61&data=05%7C02%7Cpeter.fowler%40qlik.com%7C09a1ef8e3eba4fd35bc508dc06864a81%7Cc21eeb5ff5a644e8a997124f2f7a497c%7C0%7C0%7C638392421077963676%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=njaLo3xegPjoD4AcU6WY5VIye2fCeZmA6fLIKFysoDM%3D&reserved=0

**Comment by GreenRover** [comment]
Sorry there is nothing helpful in this response. 
I still not understand why: `<rpc><show><config-sync></config-sync></show></rpc>`
Would provide better information's than: `<rpc><show><config-sync><database/><router/></config-sync></show></rpc>`
In your issue, solace provided no reasonable answer to this question.

**Comment by fowlerp-qlik** [comment]
I agree. I don't have a good understanding in the config-sync area with respect to these different queries. Is there a way to force the event broker pair into this or equivalent error condition?

**Comment by GreenRover** [comment]
For a reproducer please ask solace. That would help me alot.

**Comment by GreenRover** [comment]
Solace provided an explanation:

1. We know that for your specific case, config-sync is down due to an issue with replication.

2. "show config-sync" is the global config-sync status.
This takes care of everything including remote replication brokers that are uncontactable.

3. "show config-sync database router" only shows the status of the router table.
This table covers configurations that are not part of VPNs. For example, ldap-profiles.
These objects are not synced across replication.

So, for this particular case, it's expected that "show config-sync database router" is fully operational because it has nothing to do with replication.

4. (Not part of your question).
"show config-sync database message-vpn <name>" shows the local status of the VPN's table.
For replication active brokers, this doesn't display the state of the replication standby brokers.

"show config-sync database message-vpn <name> remote" shows the last known remote status for replication.
If config-sync never came up in the past, there may be no last known remote state.
 

There for i added a new endpoint `ConfigSync`
